approved_variables_file: data/approved_variables.csv
fuzzy_match_threshold: 80
checks:
  default_service_task_name: true
  validate_variables: true
report:
  output_file: reports/report.html
  template_file: templates/report_template.html
