approved_variables_file: src/main/resources/data/approved_variables.csv
fuzzy_match_threshold: 30
checks:
  default_service_task_name: true
  validate_variables: true
report:
  output_file: src/main/resources/reports/report.html
  template_file: src/main/resources/templates/report_template.html
